apiVersion: apps/v1
kind: Deployment
metadata:
  name: converTemp
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: converTemp
        image: patriciapadilha/conversao-temperatura:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: converTemp-service
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort
